apiVersion: v1
kind: Secret
name: mas-mongo-ce-admin-password
type: Opaque
stringData:
  password: {{ .Values.mongo-ce.mongo-ce-secret.password }}



----
apiVersion: v1
kind: Secret
name: mas-mongo-ce-cert-secret
data: 
  tls.crt: {{ .Values.mongo-ce.mongo-ce-secret.crt }}
  tls.key: {{ .Values.mongo-ce.mongo-ce-secret.key }}
